### ISSUE TITLE
Cannot complete QA test on resource because of blank screen

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#520]
The last step on second run of design tests for resources is to login as a non-admin user to verify that resource appears correctly. However, because of the issue #516, a non-admin user cannot login, therefore, I cannot finish the test run.

**Comment by GeorgeBellTMH** [comment]
This should be resolved.

**Comment by GeorgeBellTMH** [comment]
Please advise...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this issue remains active. I cannot create a new user therefore cannot complete the test.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH actually, I'm closing this as the issue is now different. No blank screen, but I created an issue for profile completion
