### ISSUE TITLE
Remove "Reply" button from replies

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#638]
Currently, the "reply" button sits on every single post made. However, our infrastructure only allows for replies to be made to the original post. Can we make it so that the "reply" button doesn't appear on reply comments? 

Alternatively, make it so that the reply is just adding another reply to the original thread?

**Comment by GeorgeBellTMH** [comment]
What happens now? I thought it would just add it to the bottom of the replies?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH right now, when the user clicks "reply" on the original post, a reply gets added to the bottom of the replies. However, if the user clicks "reply" on a reply, the user is able to submit a comment, but it doesn't appear anywhere.

**Comment by JonEsparaz** [comment]
I'm trying to take a look at this, but I can't log in...

Replies on replies should not be a thing. @lucastbelem can you please provide a screenshot? Also, what message board does the issue occur on?

**Comment by JonEsparaz** [comment]
I just saw the issue. Who decided to change the design and move the reply button?

I was under the impression we wanted this to be like a Facebook comments section, so the new design fundamentally does not make sense. In my opinion, we should revert back to how I had things originally.

**Comment by JonEsparaz** [comment]
Changes originated in https://github.com/jesus-collective/mobile/pull/631. 

I am not sure why this was commented out:

@mmacedom and @GeorgeBellTMH made these changes. I will leave this in their hands.

**Comment by lucastbelem** [comment]
Hey man,

I made the call on the design change cause I thought it better reflected
button design on Figma. As for the location of the button, I can't remember
where exactly you had it before, so I'm having a hard time remembering why
I moved it.
But I'm happy to revert if there was a reason for the design and placement
that I missed or misunderstood.

I think I asked to move it into the box for design purposes as well...cause
in figma, in courses, the button is in the comment itself. But if that
doesn't work now with the infrastructure, I'm happy to return.

I did have an interesting piece of UX feedback. The course stakeholder
asked whether it's possible (like in Facebook) to place the text box for
input below the comment you're replying to so that user is clear on what
he's replying to.

If you already had that way, that's my bad then, Jon. I jumped the gun and
asked Mateus to modify. Sorry dude!

**Comment by lucastbelem** [comment]
I'm more concerned right though with you not being able to login...were you
trying to get in on Dev or beta? What did you see? Was it a blank screen
with url ending in payment3?

**Comment by JonEsparaz** [comment]
> I'm more concerned right though with you not being able to login...were you trying to get in on Dev or beta? What did you see? Was it a blank screen with url ending in payment3? 

@lucastbelem I was not able to log in on dev or beta (localhost works).

**Comment by lucastbelem** [comment]
Hey Jon,

And do you just anything? Or just a blank screen?

Re replies:

Can you remind me - was the reply button outside of every comment
(including replies) or just original comments?
Did the text input field move to the location of the reply or was it
stationary at the top?

**Comment by JonEsparaz** [comment]
> I made the call on the design change cause I thought it better reflected button design on Figma. As for the location of the button, I can't remember where exactly you had it before, so I'm having a hard time remembering why I moved it. But I'm happy to revert if there was a reason for the design and placement that I missed or misunderstood. I think I asked to move it into the box for design purposes as well...cause in figma, in courses, the button is in the comment itself. But if that doesn't work now with the infrastructure, I'm happy to return.

The button can stay in the box if that meets the design requirements better, but as mentioned in https://github.com/jesus-collective/mobile/issues/638#issuecomment-770286470, there's a clear issue with the implementation. I'm struggling to figure out why this change was merged.

Here's my counter to that design choice, if you have a message thread with 20+ replies, and you want to reply, it would be inconvenient to scroll all the way back to the parent message to click the reply. By the logic, it makes sense for the button to be at the bottom of the entire thread (where I originally placed it; like on Facebook).

> I did have an interesting piece of UX feedback. The course stakeholder asked whether it's possible (like in Facebook) to place the text box for input below the comment you're replying to so that user is clear on what he's replying to.

Yes, I thought of this too. Definitely possible, just a little time consuming. As I mentioned in https://github.com/jesus-collective/mobile/pull/560, the rich text editor we use is a pain to work with in React Native. It would be easier if message boards just used a standard [TextInput](https://reactnative.dev/docs/textinput) component.

**Comment by lucastbelem** [comment]
Sorry, sent that too soon. I'll read through shortly and respond.

**Comment by JonEsparaz** [comment]
> And do you just anything? Or just a blank screen? 

Just a blank screen.

> Can you remind me - was the reply button outside of every comment (including replies) or just original comments? 

The reply button was at the bottom of the _thread_.

So like:
```
PARENT MESSAGE
      REPLY
      REPLY
      ....
      REPLY
      (reply button)
```
 
> Did the text input field move to the location of the reply or was it stationary at the top?

The text input is stationary.

**Comment by JonEsparaz** [comment]
@lucastbelem screenshot of the old design:

![image](https://user-images.githubusercontent.com/48423418/106369592-c6c78580-6320-11eb-8e3e-ddb481cbc2b8.png)

Also, a was mistaken, Facebook has a reply button after each message (parent-level messages _and_ replies), so we can do that, but there's logic in the code that needs to be modified.

![image](https://user-images.githubusercontent.com/48423418/106369663-540ada00-6321-11eb-94c7-6d5fc816f67d.png)

**Comment by lucastbelem** [comment]
@JonEsparaz this is super helpful. Sorry that I needed to be walked through that again. There is a lot going on and my brain is a bit foggy.

Ok this all helped me remember the reason for the design change in terms of moving the button...it's because in course assignments (which I think uses the same components) comments are collapsable and expandable, similarly to Facebook, where you don't see the replies until you press reply yourself. So the reply button is in the original post box.

@mmacedom made the changes for me and he didn't know the details of what we wanted to implement here so my guess is that he moved the button to the replies not knowing that wouldn't work. 

It's all good though. Let's do this:

@GeorgeBellTMH can you please revert to Jon's original implementation of this? Let's stay focused on getting curriculum across the finish line. Then next week let's all circle back to this to discuss/figure out the figma design, moving the button and collapsable/expandable assignments/comments.

I hope that helps resolve the situation for now and we'll discuss changes in the coming days.

Thanks for walking me through all of that again @JonEsparaz and for the work you put into it, and @mmacedom for making the changes. And @GeorgeBellTMH for going back and forth while getting curriculum ready.

Thanks team!

**Comment by JonEsparaz** [comment]
> Ok this all helped me remember the reason for the design change in terms of moving the button...it's because in course assignments (which I think uses the same components) comments are collapsable and expandable, similarly to Facebook, where you don't see the replies until you press reply yourself. So the reply button is in the original post box.

I see, but I checked Figma and I have a different interpretation.

I believe the assignment has a top-level prompt, and then all responses are just messages (not replies). So the entire message board should expand/collapse and replies are turned off.

Button says comment (not reply):
![image](https://user-images.githubusercontent.com/48423418/106371293-cafb9f00-6330-11eb-98ae-b5b771bef6a8.png)

When expanded, there is no indentation, which suggests that these are top-level messages, not replies:
![image](https://user-images.githubusercontent.com/48423418/106371302-da7ae800-6330-11eb-94fa-7aeb805334c1.png)

The feature you were trying to implement should not be related to the replies functionality IMO.

**Comment by GeorgeBellTMH** [comment]
Ok I have fixed the reply button, all of them now reply to the parent..

I'm making another ticket to clean up the courses version (which needed work to begin with before the reply feature)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this doesn't seem to be fixed.

The button still appears in the reply and if I user presses it, the reply doesn't go through (which is good, but the button shouldn't be there at all). 

This is a test from a group:

<img width="856" alt="Screen Shot 2021-02-10 at 1 19 00 PM" src="https://user-images.githubusercontent.com/48295718/107556744-cd6abe00-6ba6-11eb-99a6-b2cd3d5c8215.png">

**Comment by lucastbelem** [comment]
@GeorgeBellTMH could we fix this and this move it all to beta?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH or we can just make it so that replying replies to the parent comment.
